# Generated by Django 3.1 on 2020-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
