# Generated by Django 3.1 on 2020-08-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='XS57AM2H0', max_length=9),
        ),
    ]
